### ISSUE TITLE
Read & Write permissions don't get granted on API lvl 29 (maybe lower too)

### ISSUE THREAD

**Issue by Leonidius20** [Leonidius20/RTLnotepad#11]

**Comment by Insiderser** [comment]
Android 10 introduced scoped storage. See https://developer.android.com/training/data-storage#scoped-storage and https://blog.mindorks.com/understanding-the-scoped-storage-in-android

**Comment by Leonidius20** [comment]
> Android 10 introduced scoped storage. See https://developer.android.com/training/data-storage#scoped-storage and https://blog.mindorks.com/understanding-the-scoped-storage-in-android

Thank you, that was really relpful!
